#!/bin/bash
#
# This file is part of the Metal3 project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2019 Red Hat, Inc.
#

set +e

function clone_repo() {
    REPO_PATH=${REPO_PATH:-$HOME}
    DEST="${REPO_PATH}/$1"
    echo "Syncing $1"

    if [ ! -d $DEST ]; then
        mkdir -p $DEST
        git clone $2 $DEST
    fi

    pushd $DEST

    git am --abort 2&>/dev/null || true
    #git checkout master
    git checkout feature/config_cpu_mem
    git fetch origin
    git rebase origin/master
    popd
}

function validations() {
    # Common duties to perform before the script execution
    BASE_PATH="$(pwd)"
    REPO_PATH="${BASE_PATH}/env"
    mkdir -p "${REPO_PATH}"

    if [[ ! -e ${REPO_PATH} ]]; then
        echo "Error: File or Folder doesn't exists"
        exit -1
    fi
}

function deploy() {
    # Create empty config to work with default values
    create_dummy_config metal3-dev-env

    # Use the $1 repo to perform a make command over it
    cd ${REPO_PATH}/$1
    make
}

function create_dummy_config() {
    # Create config on dev env project
    if [[ ! -f "${REPO_PATH}/$1" ]]; then
        touch "${REPO_PATH}/$1/config_$(whoami).sh"
        chmod 755 "${REPO_PATH}/$1/config_$(whoami).sh"

        # Configure VMs
        echo 'VM_EXTRADISKS="true"' >> "${REPO_PATH}/$1/config_$(whoami).sh"
        echo 'NUM_MASTERS="1"' >> "${REPO_PATH}/$1/config_$(whoami).sh"
        echo 'NUM_WORKERS="1"' >> "${REPO_PATH}/$1/config_$(whoami).sh"
    fi
}

validations
#clone_repo metal3-dev-env https://github.com/metal3-io/metal3-dev-env.git
clone_repo metal3-dev-env https://github.com/jparrill/metal3-dev-env.git
deploy metal3-dev-env
